apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats-streaming:0.17.0
          args:
            [
              '-p',
              '4222',
              '-m',
              '8222',
              '-hbi', #heart beat, is like a little request that NATS sends to its connected clients as a health check
              '5s', #hbi specifies how often the health check requests are sent to clients
              '-hbt', # heart beat period for how long the client has to respond to the health check
              '5s',
              '-hbf', #number of times a client can fail before NATS believes the connection to the client is dead
              '2',
              '-SD',
              '-cid', #cluster id
              'ticketing'
            ] #arguments to provide to the primary command that gets executed when the container is build from this image
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222